name: CI

on:
  schedule:
  - cron: "0 12 * * *" # Every day at 1200 UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Update Daily Silksong News embed in index.html
        run: |
          git checkout gh-pages
          . updateDsnEmbedLink.sh $API_KEY
          git checkout -
